### PR TITLE
Updated to v0.26 merge;

### PR DESCRIPTION
**Pull request by twiddli**

### CODE REVIEW

**Comment by HASJ** [comment]
So much hard work! I can already see this will be the best EH manager.

**Comment by CuddleBear92** [comment]
mhm indeed thats alot of work.
looking to be the best manga manager by far IMO.

any news on this? https://github.com/Pewpews/happypanda/issues/32
mainly the info.txt import as most of my collection already has that and would import smoothly from that.

i have yet to actually start using your program because of it sadly.

**Comment by twiddli** [comment]
Thank you for the compliments!

About parsing the `info.txt` #32, I held it off because i wanted to implement a customizable lexer that would make parsing text files such as those much easier. It's too advanced to pull off in a short amount of time unfortunately so the feature won't be ready anytime soon. Sorry about that.

**Comment by CuddleBear92** [comment]
:( oh well, i guess i wont be using the app just yet then sadly :/
anyway, keep up the good work! ill keep stalking in the shades i guess :D

**Pull request merged**
